config/routes.rb
TodoList::Application.routes.draw do

  resources :list_items

  resources :categories

  resources :sales

  resources :todos

  get "static_page/new"
  get "static_page/landing"
  devise_for :users

   root 'static_page#landing'

  

end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  belongs_to :todo
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_filter :authenticate_user!, except: [:index] 
  before_action :set_list_item, only: [:show, :edit, :update, :destroy]

  # GET /list_items
  # GET /list_items.json
  def index
    @list_items = ListItem.all
  end

  # GET /list_items/1
  # GET /list_items/1.json
  def show
  end

  # GET /list_items/new
  def new
    @list_item = ListItem.new
  end

  # GET /list_items/1/edit
  def edit
  end

  # POST /list_items
  # POST /list_items.json
  def create
    @list_item = ListItem.new(list_item_params)

    respond_to do |format|
      if @list_item.save
        format.html { redirect_to @list_item, notice: 'List item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @list_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_items/1
  # PATCH/PUT /list_items/1.json
  def update
    respond_to do |format|
      if @list_item.update(list_item_params)
        format.html { redirect_to @list_item, notice: 'List item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1
  # DELETE /list_items/1.json
  def destroy
    @list_item.destroy
    respond_to do |format|
      format.html { redirect_to list_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_item
      @list_item = ListItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_item_params
      params.require(:list_item).permit(:items)
    end
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/views/list_items/_form.html.erb
<%= simple_form_for(@list_item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :items %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/list_items/edit.html.erb
<h1>Editing list_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @list_item %> |
<%= link_to 'Back', list_items_path %>

app/views/list_items/index.html.erb
<h1>Listing list_items</h1>

<table>
  <thead>
    <tr>
      <th>Items</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @list_items.each do |list_item| %>
      <tr>
        <td><%= list_item.items %></td>
        <td><%= link_to 'Show', list_item %></td>
        <td><%= link_to 'Edit', edit_list_item_path(list_item) %></td>
        <td><%= link_to 'Destroy', list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List item', new_list_item_path %>

app/views/list_items/new.html.erb
<h1>New list_item</h1>

<%= render 'form' %>

<%= link_to 'Back', list_items_path %>

app/views/list_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Items:</strong>
  <%= @list_item.items %>
</p>

<%= link_to 'Edit', edit_list_item_path(@list_item) %> |
<%= link_to 'Back', list_items_path %>