config/routes.rb
TodoList::Application.routes.draw do

  resources :list_items

  resources :categories

  resources :sales

  resources :todos

  get "static_page/new"
  get "static_page/landing"
  devise_for :users

   root 'static_page#landing'

  

end

app/models/sale.rb
class Sale < ActiveRecord::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_filter :authenticate_user!, except: [:index] 
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sale }
      else
        format.html { render action: 'new' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:number, :name, :price)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= simple_form_for(@sale) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :number %>
    <%= f.input :name %>
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<div class = "container">
  <div class ="row">
    <div class ="col-xs-12 col-sm-12 col-md-10 col-md-offset-1">
      <h1>Sales Report</h1>
      </div>
    <div class = "col-xs-12 col-sm-12 col-md-4 col-md-offset-1 row_space">
      <%= pie_chart @sales.map { |s| [s.name, s.price] } %>
    </div>
    <div class = "col-xs-12 col-sm-12 col-md-6 row_space">
      <%= bar_chart @sales.map { |s| [s.name, s.price] }%>
    </div>
    <div class = "col-xs-12 col-sm-12 col-md-4 col-md-offset-1 row_space">
      <%= line_chart @sales.map { |s| [s.id, s.number]} %>
    </div>
    <div class = "col-xs-12 col-sm-12 col-md-6 row_space">
      <%= column_chart @sales.map { |s| [s.name, s.price] } %>
    </div>
    <div class = "col-xs-12 col-sm-12 col-md-10 col-md-offset-1 row_space">
      <%= area_chart @sales.map { |s| [s.number, s.price] }  %>
    </div>
  </div>
  <div class = "row">
    <div class = "col-xs-12 col-sm-12 col-md-10 col-md-offset-1 row_space">
      <table class= "table table-hover">
        <thead>
          <tr>
            <th>Number</th>
            <th>Name</th>
            <th>Created_at</th>
            <th>Price</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @sales.each do |sale| %>
            <tr>
              <td><%= sale.number %></td>
              <td><%= sale.name %></td>
              <td><%= sale.created_at.to_date %></td>
              <td><%= sale.price %></td>
              <td><%= link_to 'Show', sale %></td>
              <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
              <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Sale', new_sale_path %>
    </div>
  </div>
</div>

app/views/sales/new.html.erb
<h1>New sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @sale.number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @sale.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @sale.price %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>